// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_5iGnwJK5hTGY4IMBeeAcX58S3-a03XE',
    appId: '1:153659216088:web:ab88092bb6b20bebee87ad',
    messagingSenderId: '153659216088',
    projectId: 'just-eat-b6eef',
    authDomain: 'just-eat-b6eef.firebaseapp.com',
    databaseURL: 'https://just-eat-b6eef-default-rtdb.firebaseio.com',
    storageBucket: 'just-eat-b6eef.appspot.com',
    measurementId: 'G-R85F7CBHL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8GUBanK7OGdop4kXDJugDFQ48S3hm64A',
    appId: '1:153659216088:android:514f231f9dad6164ee87ad',
    messagingSenderId: '153659216088',
    projectId: 'just-eat-b6eef',
    databaseURL: 'https://just-eat-b6eef-default-rtdb.firebaseio.com',
    storageBucket: 'just-eat-b6eef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuYmbXnPDxDE750ZlpmvNle397XMKZW1M',
    appId: '1:153659216088:ios:135b2020419a4740ee87ad',
    messagingSenderId: '153659216088',
    projectId: 'just-eat-b6eef',
    databaseURL: 'https://just-eat-b6eef-default-rtdb.firebaseio.com',
    storageBucket: 'just-eat-b6eef.appspot.com',
    androidClientId: '153659216088-i5itjvblim3ngk5v3u26tapc008ghiu9.apps.googleusercontent.com',
    iosClientId: '153659216088-e9midjc7b8ova593th3o7buql3icqdha.apps.googleusercontent.com',
    iosBundleId: 'com.groceryseller.grocerySeller',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuYmbXnPDxDE750ZlpmvNle397XMKZW1M',
    appId: '1:153659216088:ios:135b2020419a4740ee87ad',
    messagingSenderId: '153659216088',
    projectId: 'just-eat-b6eef',
    databaseURL: 'https://just-eat-b6eef-default-rtdb.firebaseio.com',
    storageBucket: 'just-eat-b6eef.appspot.com',
    androidClientId: '153659216088-i5itjvblim3ngk5v3u26tapc008ghiu9.apps.googleusercontent.com',
    iosClientId: '153659216088-e9midjc7b8ova593th3o7buql3icqdha.apps.googleusercontent.com',
    iosBundleId: 'com.groceryseller.grocerySeller',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_5iGnwJK5hTGY4IMBeeAcX58S3-a03XE',
    appId: '1:153659216088:web:eebe431d6640b6d7ee87ad',
    messagingSenderId: '153659216088',
    projectId: 'just-eat-b6eef',
    authDomain: 'just-eat-b6eef.firebaseapp.com',
    databaseURL: 'https://just-eat-b6eef-default-rtdb.firebaseio.com',
    storageBucket: 'just-eat-b6eef.appspot.com',
    measurementId: 'G-37MGNVBWFG',
  );
}
